import {test,expect} from '@playwright/test';
const dataKey='apartment-booking-manager:v1';
const state={version:1,migrations:{originalDemoRemoved:true},apartments:[{id:'language-fixture',name:'Apartamentul meu',address:'Strada fictivă',city:'Oraș Test'}],bookings:[{id:'language-booking',apartmentId:'language-fixture',guest:'Nume Client',phone:'0700000000',checkIn:'2026-10-10',checkOut:'2026-10-15',status:'confirmed'}]};
for(const locale of ['ro-RO','en-US','de-DE']){
 test('initial language '+locale,async({browser})=>{const context=await browser.newContext({locale});const page=await context.newPage();await page.goto('/');await expect(page.locator('html')).toHaveAttribute('lang',locale==='ro-RO'?'ro':'en');await expect(page.locator('#timeline .empty')).toHaveText(locale==='ro-RO'?'Adaugă primul apartament pentru a începe.':'Add your first apartment to get started.');await context.close();});
}
test('manual language persists; user data, current period and unsaved fields survive',async({page})=>{
 await page.clock.install({time:new Date('2026-10-06T09:00:00Z')});await page.addInitScript(s=>localStorage.setItem('apartment-booking-manager:v1',JSON.stringify(s)),state);await page.goto('/');const before=await page.evaluate(key=>localStorage.getItem(key),dataKey);
 await page.locator('.top [data-language="en"]').click();await expect(page.locator('h1')).toHaveText('Reservation calendar');await expect(page.locator('.month-label').first()).toHaveText('October 2026');await expect(page.locator('.apartment-label strong')).toHaveText('Apartamentul meu');await expect(page.locator('#range')).toHaveText('04/10/2026 – 02/11/2026');
 expect(await page.evaluate(key=>localStorage.getItem(key),dataKey)).toBe(before);await page.reload();await expect(page.locator('html')).toHaveAttribute('lang','en');
 await page.getByRole('button',{name:'+ Reservation',exact:true}).click();await page.getByLabel('Guest name',{exact:true}).fill('Draft client');await page.getByLabel('Phone',{exact:true}).fill('0700111222');await page.getByLabel('Check-in (DD/MM/YYYY)',{exact:true}).fill('28/10/2026');await page.locator('#editor [data-language="ro"]').click();await expect(page.getByLabel('Numele clientului',{exact:true})).toHaveValue('Draft client');await expect(page.getByLabel('Check-in (DD/MM/YYYY)',{exact:true})).toHaveValue('28/10/2026');await expect(page.locator('#editor-title')).toHaveText('Adaugă rezervare');await page.locator('#editor [data-language="en"]').click();await expect(page.getByLabel('Guest name',{exact:true})).toHaveValue('Draft client');
 await page.getByLabel('Check-in (DD/MM/YYYY)',{exact:true}).fill('10/10/2026');await page.getByLabel('Check-out (DD/MM/YYYY)',{exact:true}).fill('12/10/2026');await page.locator('#editor').getByRole('button',{name:'Save',exact:true}).click();await expect(page.locator('#form-error')).toHaveText('The dates overlap an existing reservation for this apartment.');await page.locator('#editor [data-language="ro"]').click();await expect(page.locator('#form-error')).toHaveText('Perioada se suprapune cu o rezervare existentă pentru acest apartament.');expect(await page.evaluate(key=>localStorage.getItem(key),dataKey)).toBe(before);
});
test('English forms: date validation, CRUD, same-day adjacency and local persistence',async({page})=>{
 await page.goto('/');await page.locator('.top [data-language="en"]').click();await page.getByRole('button',{name:'+ Apartment',exact:true}).click();await page.getByLabel('Name / identification',{exact:true}).fill('Apartament Real Test');await page.getByLabel('Address',{exact:true}).fill('Adresă Test');await page.getByLabel('Town / city',{exact:true}).fill('Localitate Test');await page.locator('#editor').getByRole('button',{name:'Save',exact:true}).click();
 async function booking(guest,checkIn,checkOut){await page.getByRole('button',{name:'+ Reservation',exact:true}).click();await page.getByLabel('Guest name',{exact:true}).fill(guest);await page.getByLabel('Phone',{exact:true}).fill('0700000000');await page.getByLabel('Check-in (DD/MM/YYYY)',{exact:true}).fill(checkIn);await page.getByLabel('Check-out (DD/MM/YYYY)',{exact:true}).fill(checkOut);await page.locator('#editor').getByRole('button',{name:'Save',exact:true}).click();}
 await booking('Client A','31/02/2026','02/03/2026');await expect(page.locator('#form-error')).toHaveText('The date is invalid.');await page.getByLabel('Check-in (DD/MM/YYYY)',{exact:true}).fill('10/10/2026');await page.getByLabel('Check-out (DD/MM/YYYY)',{exact:true}).fill('12/10/2026');await page.locator('#editor').getByRole('button',{name:'Save',exact:true}).click();await booking('Client B','12/10/2026','15/10/2026');
 await page.getByRole('button',{name:'Oct 2026',exact:true}).click();await expect(page.locator('.handover')).toHaveCount(1);await page.reload();await expect(page.locator('html')).toHaveAttribute('lang','en');expect(await page.evaluate(key=>JSON.parse(localStorage.getItem(key)).bookings.length,dataKey)).toBe(2);
 await page.getByRole('button',{name:'Oct 2026',exact:true}).click();await page.locator('.booking').first().click();await expect(page.locator('#editor-title')).toHaveText('Reservation details');await page.getByLabel('Guest name',{exact:true}).fill('Client A updated');await page.locator('#editor').getByRole('button',{name:'Save',exact:true}).click();await expect(page.locator('.booking').first()).toHaveText('Client A updated');
 await page.locator('.booking').first().click();await page.locator('#editor').getByRole('button',{name:'Delete',exact:true}).click();await expect(page.locator('#confirmation-text')).toHaveText('Delete this reservation? This action cannot be undone.');await page.locator('#confirmation').getByRole('button',{name:'Delete permanently',exact:true}).click();await expect(page.locator('.booking')).toHaveCount(1);
 await page.locator('.timeline-row .apartment-label').click();await page.getByLabel('Name / identification',{exact:true}).fill('Apartament renamed');await page.locator('#editor').getByRole('button',{name:'Save',exact:true}).click();await expect(page.locator('.timeline-row .apartment-label strong')).toHaveText('Apartament renamed');await page.locator('.timeline-row .apartment-label').click();await page.locator('#editor').getByRole('button',{name:'Delete',exact:true}).click();await expect(page.locator('#confirmation-text')).toContainText('1 reservations');await page.locator('#confirmation').getByRole('button',{name:'Delete permanently',exact:true}).click();await expect(page.locator('.timeline-row')).toHaveCount(0);
});
for(const width of [320,360,412,840]){
 test('English layout '+width,async({page})=>{await page.setViewportSize({width,height:900});await page.goto('/');await page.locator('.top [data-language="en"]').click();await expect(page.locator('.day-heading')).toHaveCount(30);await expect(page.locator('.month-option')).toHaveCount(12);expect(await page.evaluate(()=>document.documentElement.scrollWidth<=document.documentElement.clientWidth)).toBe(true);await page.screenshot({path:`test-results/EN-${width}.png`,fullPage:true});});
}
