import {dayNumber,isoDay,today,validateApartment,validateBooking} from './domain.js';
import {createLocalRepository} from './storage.js';
import {demoState} from './demo.js';
import {renderTimeline} from './timeline.js';
const $=id=>document.getElementById(id);
let repository,state,blocked=false;
try {repository=createLocalRepository();state=repository.load();if(!state){state=demoState();repository.save(state);}}
catch(error){state={version:1,apartments:[],bookings:[]};blocked=true;$('notice').textContent='Salvarea locală nu poate fi accesată sau datele sunt incompatibile. Datele existente nu au fost suprascrise. Verifică permisiunile browserului înainte de a continua.';}
let start=dayNumber(today())-2,days=14,editing;
const dateFormat=new Intl.DateTimeFormat('ro',{day:'numeric',month:'long',year:'numeric',timeZone:'UTC'});
function render(){renderTimeline($('timeline'),state,start,days,{editApartment:a=>open('apartment',a),editBooking:b=>open('booking',b),newBooking:(apartmentId,checkIn)=>open('booking',null,{apartmentId,checkIn})});$('range').textContent=`${dateFormat.format(new Date(start*86400000))} – ${dateFormat.format(new Date((start+days-1)*86400000))}`;$('summary').textContent=`${state.apartments.length} apartamente · ${state.bookings.length} rezervări`;$('add-booking').disabled=blocked||!state.apartments.length;$('add-apartment').disabled=blocked;}
function field(labelText,name,value='',type='text') {const label=document.createElement('label');label.textContent=labelText;const input=document.createElement('input');input.name=name;input.type=type;input.value=value;input.required=true;input.maxLength=name==='phone'?30:150;label.append(input);$('fields').append(label);return input;}
function open(kind,item=null,defaults={}) {if(blocked)return;editing={kind,id:item?.id};$('editor-form').reset();$('fields').replaceChildren();$('form-error').textContent='';$('delete').hidden=!item;$('editor-title').textContent=kind==='apartment'?(item?'Detalii apartament':'Adaugă apartament'):(item?'Detalii rezervare':'Adaugă rezervare');
 if(kind==='apartment'){field('Nume / identificare','name',item?.name);field('Adresă','address',item?.address);field('Localitate','city',item?.city);}else{const label=document.createElement('label');label.textContent='Apartament';const select=document.createElement('select');select.name='apartmentId';select.required=true;for(const a of state.apartments){const option=document.createElement('option');option.value=a.id;option.textContent=a.name;select.append(option);}select.value=item?.apartmentId||defaults.apartmentId||state.apartments[0]?.id;label.append(select);$('fields').append(label);field('Numele clientului','guest',item?.guest);field('Telefon','phone',item?.phone,'tel');const checkIn=item?.checkIn||defaults.checkIn||today();field('Check-in','checkIn',checkIn,'date');field('Check-out','checkOut',item?.checkOut||isoDay(dayNumber(checkIn)+1),'date');}
 $('editor').showModal();}
function persist(next) {try{repository.save(next);state=next;render();return true;}catch(e){$('form-error').textContent='Datele nu au putut fi salvate. Verifică spațiul și permisiunile browserului. Modificarea nu a fost aplicată.';return false;}}
$('editor-form').onsubmit=e=>{e.preventDefault();const values=Object.fromEntries(new FormData(e.target));for(const key in values) values[key]=values[key].trim();const item={...values,id:editing.id||crypto.randomUUID()};try{editing.kind==='apartment'?validateApartment(item):validateBooking(item,state);const key=editing.kind==='apartment'?'apartments':'bookings';const next={...state,[key]:editing.id?state[key].map(v=>v.id===editing.id?item:v):[...state[key],item]};if(persist(next))$('editor').close();}catch(error){$('form-error').textContent=error.message;}};
$('delete').onclick=()=>{const apartment=editing.kind==='apartment';const count=apartment?state.bookings.filter(b=>b.apartmentId===editing.id).length:0;$('confirmation-text').textContent=apartment?`Ștergi acest apartament${count?` și cele ${count} rezervări asociate`:''}? Această acțiune nu poate fi anulată.`:'Ștergi această rezervare? Această acțiune nu poate fi anulată.';$('confirmation').returnValue='cancel';$('confirmation').showModal();};
$('confirmation').addEventListener('close',()=>{if($('confirmation').returnValue!=='delete')return;const next=editing.kind==='apartment'?{...state,apartments:state.apartments.filter(a=>a.id!==editing.id),bookings:state.bookings.filter(b=>b.apartmentId!==editing.id)}:{...state,bookings:state.bookings.filter(b=>b.id!==editing.id)};if(persist(next))$('editor').close();});
$('close').onclick=$('cancel').onclick=()=>$('editor').close();$('add-apartment').onclick=()=>open('apartment');$('add-booking').onclick=()=>open('booking');$('prev').onclick=()=>{start-=days;render();};$('next').onclick=()=>{start+=days;render();};$('today').onclick=()=>{start=dayNumber(today())-2;render();};$('days').onchange=e=>{days=Number(e.target.value);render();};render();
