// Add languages here; application and domain data never contain translated values.
export const LANGUAGE_KEY='apartment-booking-manager:language';
export const translations={
 ro:{
  version:'Rezervări · versiunea BASIC',local:'● Salvare pe acest dispozitiv',eyebrow:'SPAȚIU PENTRU FIECARE SEJUR',heading:'Calendarul rezervărilor',subtitle:'Toate apartamentele, într-o singură privire.',addApartment:'+ Apartament',addBooking:'+ Rezervare',calendar:'Calendar rezervări',previous:'Perioada anterioară',next:'Perioada următoare',today:'Astăzi',view:'Vizualizare',thirtyDays:'30 zile',chooseMonth:'Selectează luna calendarului',previousYear:'Anul precedent',nextYear:'Anul următor',free:'Liber',confirmed:'Confirmată',unconfirmed:'Neconfirmată',handover:'Schimb în aceeași zi',halfDays:'½ zi plecare · ½ zi sosire',apartmentsHeading:'APARTAMENTE',summary:'{apartments} apartamente · {bookings} rezervări',calendarHint:'Selectează o rezervare pentru detalii. Apasă o zi liberă pentru a adăuga.',storageNote:'Datele sunt salvate în acest browser și nu sunt sincronizate între dispozitive.',close:'Închide',delete:'Șterge',cancel:'Renunță',save:'Salvează',confirmDeletion:'Confirmă ștergerea',deletePermanently:'Șterge definitiv',languageSelector:'Limba aplicației',languageSaveFailed:'Preferința de limbă nu a putut fi salvată pe acest dispozitiv.',apartmentDetails:'Detalii apartament',newApartment:'Adaugă apartament',bookingDetails:'Detalii rezervare',newBooking:'Adaugă rezervare',apartmentName:'Nume / identificare',address:'Adresă',city:'Localitate',apartment:'Apartament',bookingStatus:'Status rezervare',guest:'Numele clientului',phone:'Telefon',checkIn:'Check-in',checkOut:'Check-out',editApartment:'Modifică apartamentul',addBookingDay:'Adaugă rezervare: {apartment}, {date}',bookingDescription:'{guest} · {checkIn} → {checkOut} · {status} · {phone}',handoverDate:'Schimb de clienți: {date}',empty:'Adaugă primul apartament pentru a începe.',deleteApartment:'Ștergi acest apartament? Această acțiune nu poate fi anulată.',deleteApartmentBookings:'Ștergi acest apartament și cele {count} rezervări asociate? Această acțiune nu poate fi anulată.',deleteBooking:'Ștergi această rezervare? Această acțiune nu poate fi anulată.',storageBlocked:'Salvarea locală nu poate fi accesată sau datele sunt incompatibile. Datele existente nu au fost suprascrise. Verifică permisiunile browserului înainte de a continua.',storageSave:'Datele nu au putut fi salvate. Verifică spațiul și permisiunile browserului. Modificarea nu a fost aplicată.',required:'Completează toate câmpurile obligatorii.',invalidDate:'Data este invalidă.',dateFormat:'Introdu data în format DD/MM/YYYY.',apartmentFields:'Completează numele, adresa și localitatea.',invalidStatus:'Status de rezervare invalid.',existingApartment:'Selectează un apartament existent.',guestRequired:'Introdu numele clientului.',invalidPhone:'Introdu un număr de telefon valid (minimum 6 cifre).',dateOrder:'Check-out trebuie să fie după check-in.',overlap:'Perioada se suprapune cu o rezervare existentă pentru acest apartament.',unexpectedError:'Operația nu a putut fi efectuată. Verifică datele și încearcă din nou.',
  monthsShort:['Ian','Feb','Mar','Apr','Mai','Iun','Iul','Aug','Sep','Oct','Nov','Dec'],monthsFull:['Ianuarie','Februarie','Martie','Aprilie','Mai','Iunie','Iulie','August','Septembrie','Octombrie','Noiembrie','Decembrie'],weekdays:['dum.','lun.','mar.','mie.','joi','vin.','sâm.']
 },
 en:{
  version:'Reservations · BASIC version',local:'● Saved on this device',eyebrow:'ROOM FOR EVERY STAY',heading:'Reservation calendar',subtitle:'All apartments, at a glance.',addApartment:'+ Apartment',addBooking:'+ Reservation',calendar:'Reservation calendar',previous:'Previous period',next:'Next period',today:'Today',view:'View',thirtyDays:'30 days',chooseMonth:'Select calendar month',previousYear:'Previous year',nextYear:'Next year',free:'Free',confirmed:'Confirmed',unconfirmed:'Unconfirmed',handover:'Same-day changeover',halfDays:'½ day check-out · ½ day check-in',apartmentsHeading:'APARTMENTS',summary:'{apartments} apartments · {bookings} reservations',calendarHint:'Select a reservation for details. Select a free day to add one.',storageNote:'Data is saved in this browser and is not synced between devices.',close:'Close',delete:'Delete',cancel:'Cancel',save:'Save',confirmDeletion:'Confirm deletion',deletePermanently:'Delete permanently',languageSelector:'Application language',languageSaveFailed:'The language preference could not be saved on this device.',apartmentDetails:'Apartment details',newApartment:'Add apartment',bookingDetails:'Reservation details',newBooking:'Add reservation',apartmentName:'Name / identification',address:'Address',city:'Town / city',apartment:'Apartment',bookingStatus:'Reservation status',guest:'Guest name',phone:'Phone',checkIn:'Check-in',checkOut:'Check-out',editApartment:'Edit apartment',addBookingDay:'Add reservation: {apartment}, {date}',bookingDescription:'{guest} · {checkIn} → {checkOut} · {status} · {phone}',handoverDate:'Guest changeover: {date}',empty:'Add your first apartment to get started.',deleteApartment:'Delete this apartment? This action cannot be undone.',deleteApartmentBookings:'Delete this apartment and its {count} reservations? This action cannot be undone.',deleteBooking:'Delete this reservation? This action cannot be undone.',storageBlocked:'Local storage is unavailable or the saved data is incompatible. Existing data has not been overwritten. Check browser permissions before continuing.',storageSave:'Data could not be saved. Check available space and browser permissions. The change was not applied.',required:'Complete all required fields.',invalidDate:'The date is invalid.',dateFormat:'Enter the date in DD/MM/YYYY format.',apartmentFields:'Complete the name, address and town / city.',invalidStatus:'Invalid reservation status.',existingApartment:'Select an existing apartment.',guestRequired:'Enter the guest name.',invalidPhone:'Enter a valid phone number (at least 6 digits).',dateOrder:'Check-out must be after check-in.',overlap:'The dates overlap an existing reservation for this apartment.',unexpectedError:'The operation could not be completed. Check the data and try again.',
  monthsShort:['Jan','Feb','Mar','Apr','May','Jun','Jul','Aug','Sep','Oct','Nov','Dec'],monthsFull:['January','February','March','April','May','June','July','August','September','October','November','December'],weekdays:['Sun','Mon','Tue','Wed','Thu','Fri','Sat']
 }
};
let language='en';
export function detectLanguage(deviceLanguage=''){return /^ro(?:-|$)/i.test(deviceLanguage)?'ro':'en';}
export function initializeLanguage(options={}){
 let saved;try{saved=(options.storage??globalThis.localStorage)?.getItem(LANGUAGE_KEY);}catch{}
 language=Object.hasOwn(translations,saved)?saved:detectLanguage(options.deviceLanguage??globalThis.navigator?.language);return language;
}
export function getLanguage(){return language;}
export function selectLanguage(value,storage){
 if(!Object.hasOwn(translations,value))throw new Error('Unsupported language');language=value;
 try{(storage??globalThis.localStorage).setItem(LANGUAGE_KEY,value);return true;}catch{return false;}
}
export function t(key,values={}){const value=translations[language][key];if(value===undefined)throw new Error('Unknown translation key: '+key);return typeof value==='string'?value.replace(/\{(\w+)\}/g,(_,name)=>String(values[name]??'')):value;}
export function monthTitle(date){return `${t('monthsFull')[date.getUTCMonth()]} ${date.getUTCFullYear()}`;}
export function weekdayTitle(date){return t('weekdays')[date.getUTCDay()];}
const errors={
 'Data este invalidă.':'invalidDate','Introdu data în format DD/MM/YYYY.':'dateFormat','Completează numele, adresa și localitatea.':'apartmentFields','Status de rezervare invalid.':'invalidStatus','Selectează un apartament existent.':'existingApartment','Introdu numele clientului.':'guestRequired','Introdu un număr de telefon valid (minimum 6 cifre).':'invalidPhone','Check-out trebuie să fie după check-in.':'dateOrder','Perioada se suprapune cu o rezervare existentă pentru acest apartament.':'overlap'
};
// Adapt legacy domain errors at the UI boundary; validation and storage rules stay unchanged.
export function translateError(error){const message=error?.message??error;return t(errors[message]??(Object.hasOwn(translations.en,message)?message:'unexpectedError'));}
export function translateUI(root=document){
 root.documentElement?.setAttribute('lang',language);
 for(const el of root.querySelectorAll('[data-i18n]'))el.textContent=t(el.dataset.i18n);
 for(const el of root.querySelectorAll('[data-i18n-aria]'))el.setAttribute('aria-label',t(el.dataset.i18nAria));
 for(const el of root.querySelectorAll('[data-date-label]'))el.setAttribute('aria-label',t(el.dataset.dateLabel)+' (DD/MM/YYYY)');
 for(const el of root.querySelectorAll('[data-language]'))el.setAttribute('aria-pressed',String(el.dataset.language===language));
}
