import {t,monthTitle,weekdayTitle} from './i18n.js?v=0.3.1';
import {displayDate} from './date-format.js?v=0.2.5';
import {barGeometry,dayNumber,isoDay,today,monthSegments,handoverDays} from './domain.js?v=0.2.1';
export function renderTimeline(root,state,start,days,{editApartment,editBooking,newBooking}) {
 root.replaceChildren(); root.style.setProperty('--days',days);
 const head=document.createElement('div');head.className='timeline-head';
 const corner=document.createElement('div');corner.className='apartment-label corner';corner.textContent=t('apartmentsHeading');head.append(corner);
 const calendarHead=document.createElement('div');calendarHead.className='calendar-head';
 const months=document.createElement('div');months.className='day-grid months';
 for(const segment of monthSegments(start,days)){const month=document.createElement('div');month.className='month';month.style.gridColumn=`${segment.start+1} / span ${segment.days}`;const date=new Date((start+segment.start)*86400000);month.title=monthTitle(date);const label=document.createElement('span');label.className='month-label';label.textContent=month.title;if(segment.days<=4){month.classList.add('month-short');label.textContent=month.title.replace(/ (\d{4})$/,'\n$1');}month.append(label);months.append(month);}calendarHead.append(months);
 const dates=document.createElement('div');dates.className='day-grid';const current=dayNumber(today());
 for(let i=0;i<days;i++){const n=start+i,date=new Date(n*86400000),weekend=[0,6].includes(date.getUTCDay());const el=document.createElement('div');el.className='day-heading'+(weekend?' weekend':'')+(n===current?' current':'');const weekday=document.createElement('small');weekday.textContent=weekdayTitle(date);const num=document.createElement('strong');num.textContent=date.getUTCDate();el.append(weekday,num);dates.append(el);}calendarHead.append(dates);head.append(calendarHead);root.append(head);
 for(const a of state.apartments){const row=document.createElement('div');row.className='timeline-row';const label=document.createElement('button');label.className='apartment-label';label.title=t('editApartment');const name=document.createElement('strong');name.textContent=a.name;const address=document.createElement('small');address.textContent=`${a.city} · ${a.address}`;label.append(name,address);label.onclick=()=>editApartment(a);row.append(label);
 const track=document.createElement('div');track.className='track';const cells=document.createElement('div');cells.className='day-grid cells';
 for(let i=0;i<days;i++){const n=start+i,weekend=[0,6].includes(new Date(n*86400000).getUTCDay());const cell=document.createElement('button');cell.className='day-cell'+(weekend?' weekend':'')+(n===current?' current':'');cell.setAttribute('aria-label',t('addBookingDay',{apartment:a.name,date:displayDate(isoDay(n))}));cell.onclick=()=>newBooking(a.id,isoDay(n));cells.append(cell);}track.append(cells);
 const bookings=state.bookings.filter(b=>b.apartmentId===a.id);
 for(const b of bookings){const g=barGeometry(b,start,days);if(!g)continue;const bar=document.createElement('button');bar.className='booking '+(b.status==='unconfirmed'?'unconfirmed':'confirmed');bar.style.left=`${g.left/days*100}%`;bar.style.width=`${g.width/days*100}%`;bar.textContent=b.guest;bar.title=t('bookingDescription',{guest:b.guest,checkIn:displayDate(b.checkIn),checkOut:displayDate(b.checkOut),status:t(b.status==='unconfirmed'?'unconfirmed':'confirmed'),phone:b.phone});bar.setAttribute('aria-label',bar.title);bar.onclick=()=>editBooking(b);track.append(bar);}
 for(const date of handoverDays(bookings)){const x=dayNumber(date)-start+.5;if(x<0||x>=days)continue;const line=document.createElement('span');line.className='handover';line.style.left=`${x/days*100}%`;line.title=t('handoverDate',{date:displayDate(date)});line.setAttribute('aria-label',line.title);track.append(line);}row.append(track);root.append(row);}
 if(!state.apartments.length){const empty=document.createElement('p');empty.className='empty';empty.textContent=t('empty');root.append(empty);}
}
